#!/usr/bin/env python3

import sys
from install import *
from test import *
from perform import *

if len(sys.argv) == 2:
    if sys.argv[1] == "install":
        install()
    elif sys.argv[1] == "test":
        test()
    else:
        urls = parse(sys.argv[1])
        perform(urls, sys.argv[1])
else:
    print("Incorrect number of arguments")
    sys.exit(1)
