#!/usr/bin/env python

import sys
import test
import install
import perform

if len(sys.argv) == 2:
    if sys.argv[1] == "install":
        install.install()
    elif sys.argv[1] == "test":
        test.test()
    else:
        urls = perform.parse(sys.argv[1])
        perform.perform(urls, sys.argv[1])
else:
    print("Incorrect number of arguments")
