# Generated by Django 3.2.9 on 2021-12-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('uppackage', models.FileField(upload_to='upload/packages/')),
            ],
        ),
        migrations.DeleteModel(
            name='ZipUploaded',
        ),
    ]
