# Generated by Django 3.2.9 on 2021-12-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontsite', '0002_auto_20211204_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
