# This workflow automatically tests scoring function

name: Test-scoring

on:
    push:
      branches: [ main ]

env: 
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

jobs:
  on_build_actions:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
          architecture: x64
      
      - name: Install dependencies
        run: |
          cd Scoring
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Tests
        run: |
          cd Scoring
          python -m unittest test.py
